version: '3'

services:
    db:
      image: mysql:5.7
      ports: 
        - 3307:3307
      env_file: 
        - variable.env
    app:
        build: .
        ports: 
          - 8081:8081
        depends_on: 
          - db
        environment: 
          - DATABSE_HOST=db

    