version: '3'

services:
    db:
      image: mysql:5.7
      ports: 
        - 3306:3306
      env_file: 
        - variable.env
      environment: 
        MYSQL_USER: root  
        MYSQL_PASSWORD: mysql
        MYSQL_DATABASE: userss
      container_name: my_go_app_db
      
    app:
        build: .
        ports: 
          - 8081:8081
        depends_on: 
          - db
        environment: 
          - DATABSE_HOST=db

    